# xp-forge/json

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - curl -sSL https://dl.bintray.com/xp-runners/generic/xp-run-master.sh > xp-run
  - composer install --prefer-dist
  - echo "vendor/autoload.php" > composer.pth
  - phpenv config-rm xdebug.ini || true

script:
  - git clone https://github.com/nst/JSONTestSuite.git
  - sh xp-run xp.unittest.TestRunner src/test/php src/it/php -a JSONTestSuite
